### ISSUE TITLE
Unable to start tutorial1d (Attribute error)

### ISSUE THREAD

**Issue by mkharboutly** [fifengine/python-tutorials#1]
Hi all, 
I was trying to start the tutorial1d and when I start the run.py file, the following error occurs:" AttributeError: 'NoneType' object has no attribute 'debug' ". After digging into fife and debugging I notice that the following function must be called : pychan.init() which initialise pychan, before calling any pychan function like pychan.loadXML(). Thus I added a call to that function (pychan.init(self.engine) ) inside the Tutorial1Application class and exactly before pychan.loadXML("...") in the tutorial1.py of the tutorial1d. By initialising pychan the tutorial runs perfectly. 
Is this right, or there are something else I didn't notice?

**Comment by LinuxDonald** [comment]
Could you maybe provide an patch for it please?

**Comment by prock-fife** [comment]
Actually, the issue is because the application should be inheriting PychanApplicationBase and not ApplicationBase. 

Line 144 of tutorial1.py in tutorial 1D:
`class Tutorial1Application(ApplicationBase):`

Should actually be:
`class Tutorial1Application(PychanApplicationBase):`

**Comment by LinuxDonald** [comment]
@prock-fife is my pr correct?

**Comment by prock-fife** [comment]
@LinuxDonald looks good to me.
